### PR TITLE
use MPI.mpiexec function

### LINKED ISSUE #16: MPIClusterManagers 0.1 with MPI master: Access to undefined reference
Was testing out the new MPI changes when I ran into this:

```jl
julia> using Distributed, MPIClusterManagers

julia> man = MPIManager(; np=2)
MPI.MPIManager(np=2,launched=false,mode=MPI_ON_WORKERS)

julia> addprocs(man)
ERROR: UndefRefError: access to undefined reference
Stacktrace:
 [1] getindex at ./array.jl:788 [inlined]
 [2] popfirst! at ./array.jl:1189 [inlined]
 [3] macro expansion at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.4/Distributed/src/cluster.jl:486 [inlined]
 [4] macro expansion at ./task.jl:334 [inlined]
 [5] addprocs_locked(::MPIManager; kwargs::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.4/Distributed/src/cluster.jl:477
 [6] addprocs_locked at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.4/Distributed/src/cluster.jl:448 [inlined]
 [7] addprocs(::MPIManager; kwargs::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.4/Distributed/src/cluster.jl:441
 [8] addprocs(::MPIManager) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.4/Distributed/src/cluster.jl:435
 [9] top-level scope at REPL[10]:1
 [10] eval(::Module, ::Any) at ./boot.jl:331
 [11] eval_user_input(::Any, ::REPL.REPLBackend) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.4/REPL/src/REPL.jl:86
 [12] run_backend(::REPL.REPLBackend) at /home/degraafc/.local/share/julia/packages/Revise/0meWR/src/Revise.jl:1075
 [13] top-level scope at none:0

pkg> st
Status `~/scratch/Project.toml`
  [da04e1cc] MPI v0.13.1 #master (https://github.com/JuliaParallel/MPI.jl.git)
  [e7922434] MPIClusterManagers v0.1.0
  [8ba89e20] Distributed
```

I tried running it through the debugger but it didn't really make sense to me...

```jl
In #addprocs#37(kwargs, , manager) at /home/degraafc/.local/share/asdf/installs/julia/1.4.1/julia/share/julia/stdlib/v1.4/Distributed/src/cluster.jl:435
 437      cluster_mgmt_from_master_check()
 438
 439      lock(worker_lock)
 440      try
 441          addprocs_locked(manager::ClusterManager; kwargs...)
 442      finally
>443          unlock(worker_lock)
 444      end
 445  end

About to run: (===)(2, 2)
1|debug> n
ERROR: UndefRefError: access to undefined reference
Stacktrace:
 [1] addprocs(::MPIManager; kwargs::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}) at /home/degraafc/.local/share/asdf/installs/julia/1.4.1/julia/share/julia/stdlib/v1.4/Distributed/src/cluster.jl:443
 [2] addprocs(::MPIManager) at /home/degraafc/.local/share/asdf/installs/julia/1.4.1/julia/share/julia/stdlib/v1.4/Distributed/src/cluster.jl:435
```

### PR DESCRIPTION
**Pull request by simonbyrne**
Hopefully fix  #16.

### CODE REVIEW

**Comment by ViralBShah** [comment]
I guess the key is to figure out what's happening here and get it merged.

**Comment by ViralBShah** [comment]
@christopher-dG Can you help with this one?

**Comment by ViralBShah** [comment]
I see @simonbyrne literally just opened this PR a few hours ago. Never mind. I'm just following to see if this gets fixed. After that a whole bunch of other stuff can probably be merged and tagged.

**Comment by christopher-dG** [comment]
I ran the Elemental tests locally with this branch + MPI#master and they passed.

**Comment by christopher-dG** [comment]
This package's CI needs an update to newer Julia versions, then we'll have a better idea of how things are working.

**Comment by ViralBShah** [comment]
Won't 1.3 and 1.4 not work without the fix in Julia, which is only on the 1.5 release branch?

**Comment by simonbyrne** [comment]
Failure due to https://github.com/JuliaPackaging/BinaryBuilder.jl/pull/775.

**Pull request merged**
